# Frequency partition boundaries
ptbxl:
  uniform:
    transformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamba:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
  equal_variance:
    transformer:
      2: [5.86]
      3: [3.12, 5.86, 11.72] 
      4: [2.34, 8.98]
    mamba:
      2: [5.86]
      3: [3.12, 5.86, 11.72] 
      4: [2.34, 8.98]
    mamformer:
      2: [5.86]
      3: [3.12, 5.86, 11.72] 
      4: [2.34, 8.98]


chapman:
  uniform:
    transformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamba:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
  equal_variance:
    transformer:
      2: [4.69]
      3: [2.34, 8.98]
      4: [1.56, 5.86 12.11]
    mamba:
      2: [4.69]
      3: [2.34, 8.98]
      4: [1.56, 5.86, 12.11]
    mamformer:
      2: [4.69]
      3: [2.34, 8.98]
      4: [1.56, 5.86, 12.11]

isruc:
  uniform:
    transformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamba:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
  equal_variance:
    transformer:
      2: [1.17]
      3: [0.78, 1.56]
      4: [0.39, 1.17, 2.73] 
    mamba:
      2: [1.17]
      3: [0.78, 1.56]
      4: [0.39, 1.17, 2.73] 
    mamformer:
      2: [1.17]
      3: [0.78, 1.56]
      4: [0.39, 1.17, 2.73] 

sleep_edf:
  uniform:
    transformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamba:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
    mamformer:
      2: [25.0]
      4: [12.5, 25.0, 37.5]
  equal_variance:
    transformer:
      2: [1.17]
      3: [0.78, 1.95]
      4: [0.39, 1.17, 2.73]
    mamba:
      2: [1.17]
      3: [0.78, 1.95]
      4: [0.39, 1.17, 2.73]
    mamformer:
      2: [1.17]
      3: [0.78, 1.95]
      4: [0.39, 1.17, 2.73]
